import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Slider from "@/components/Slider";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`w-dvw h-dvh overflow-hidden ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className='w-full h-full bg-[#242424] flex overflow-hidden'>
          <Slider />
          <div className='flex-auto h-full flex flex-col justify-start'>
            <Header />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
